DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_SEG_TOKEN = "<SEG>"
DEFAULT_RLE_TOKEN = "<RLE>"
DEFAULT_CLS_TOKEN = "<CLS>"
DEFAULT_MAP_TOKEN = "<map>"
DEFAULT_INSTANCE_TOKEN = "<instance>"
DEFAULT_PSTART_TOKEN = "<p>"
DEFAULT_PEND_TOKEN = "</p>"
DEFAULT_REGION_TOKEN = "<region>"

MASK_QUESTION_LIST = [
    "Can you segment the image based on the following categories: {categories}? Please output the {task_type} segmentation masks.",
    "Can you generate {task_type} segmentation masks for this image based on the specified categories: {categories}? Please generate the {task_type} segmentation masks.",
    "Can you provide {task_type} segmentation masks for this image based on these categories: {categories}? Please provide the {task_type} segmentation masks.",
    "Could you create {task_type} segmentation masks for this image according to the specified categories: {categories}? Please create the {task_type} segmentation masks.",
    "Could you output {task_type} segmentation masks for this image that highlight the following categories: {categories}? Please output the {task_type} segmentation masks.",
    "Could you provide {task_type} segmentation masks for this image according to the specified categories: {categories}? Please respond with the {task_type} segmentation masks.",
]
# more nature questions, generated by gpt
MASK_QUESTION_LIST += [
    "I need {task_type} segmentation masks for the following categories: {categories}. Could you generate them?",
    "Please generate {task_type} segmentation masks that correspond to these categories: {categories}.",
    "For this image, could you output the {task_type} segmentation masks highlighting {categories}?",
    "Could you return the {task_type} segmentation masks for the specified categories: {categories}?",
    "Please provide the {task_type} segmentation results for the categories: {categories}.",
    "Can you show me the {task_type} segmentation masks of the objects belonging to {categories}?",
    "Generate {task_type} segmentation masks for the categories: {categories}, and output them.",
    "I would like to see {task_type} segmentation masks for these categories: {categories}. Could you produce them?",
    "Could you annotate this image with {task_type} segmentation masks for the categories: {categories}?",
    "For the given image, please output {task_type} segmentation masks corresponding to {categories}.",
]
MASK_QUESTION_LIST += [
    "What would the {task_type} segmentation masks look like if we focus on these categories: {categories}?",
    "Can you show me how the image would be segmented into {categories} using {task_type} segmentation?",
    "If I wanted to see the {task_type} segmentation for {categories}, what would it look like?",
    "Could you highlight {categories} in this image with {task_type} segmentation masks?",
    "I'd like to know how {categories} appear in the {task_type} segmentation. Can you generate that?",
    "Can you help me visualize the {task_type} segmentation of {categories} in this image?",
    "How would this image look if segmented into {categories} with {task_type} segmentation?",
    "Please show me the {task_type} segmentation masks that correspond to {categories}.",
    "Could you give me a {task_type} segmentation result that clearly shows {categories}?",
    "I'm curious to see the {task_type} segmentation for these categories: {categories}. Can you output it?",
]
CAPTION_QUESTION_LIST = [
    "Please find all instances in the image and assign color to each instance in the EXACT format: <p>instance-no<color>(R,G,B)</color></p>, then respond with {task_type} segmentation masks."
]
CAPTION_REFORMAT_QUESTION_LIST = [
    "Please find all instances in the image and assign color to each instance in the EXACT format: <p>instance</p><color>(R1,G1,B1)(R2,G2,B2)</color>, then respond with {task_type} segmentation masks."
]

MASK_CAPTION_QUESTION_LIST = [
    "Can you segment the image based on the following categories: {categories}? Please first describe the image briefly, then respond with segmentation masks.",
    "Can you generate segmentation masks for this image based on the specified categories: {categories}? Please first briefly describe the contents of the image, then respond with segmentation masks.",
    "Can you provide segmentation masks for this image based on these categories: {categories}? Please first give me a brief description of the image, then output segmentation masks.",
    "Could you create segmentation masks for this image according to the specified categories: {categories}? Please first give me a brief description of this picture, then respond with segmentation masks.",
    "Could you output segmentation masks for this image that highlight the following categories: {categories}? Please first provide me with a brief description of this photo, then respond with segmentation masks.",
    "Could you provide segmentation masks for this image according to the specified categories: {categories}. Please first describe the image briefly, then respond with segmentation masks.",
]

FOLLOWUP_QUESTION_LIST = [
    "Can you explain the mapping between each category/instance and its corresponding color in the segmentation mask?",
    "Please list the categories and instances along with the colors used for them in the segmentation result.",
    "Could you describe which category or instance is represented by which color in the mask?",
    "I'd like to know the mapping of categories/instances to colors in this segmentation. Could you provide it?",
    "Can you clarify the relationship between each object category and the color shown in the segmentation map?",
    "Please output a detailed list of categories or instances together with their assigned colors in the mask.",
    "Could you provide the color legend, showing how each category/instance is associated with a color?",
    "I'd like to see a breakdown of the segmentation mask: which categories/instances correspond to which colors?",
    "Can you summarize the mapping of segmentation colors to their respective categories and instances?",
    "Could you explain the legend of the segmentation mask — which colors correspond to which categories/instances?",
]

VISION_QUESTION_LIST = [
    "Can you segment the image based on the following regions: {regions}? Please output the corresponding segmentation mask.",
    "Can you generate segmentation masks for this image based on the specified regions: {regions}? Please generate the segmentation masks.",
    "Can you provide segmentation masks for this image based on these regions: {regions}? Please provide the segmentation masks.",
    "Could you create segmentation masks for this image according to the specified regions: {regions}? Please create the segmentation masks.",
    "Could you output segmentation masks for this image that highlight the following regions: {regions}? Please output the segmentation masks.",
    "Could you provide segmentation masks for this image according to the specified regions: {regions}? Please respond with the segmentation masks.",
]

SHORT_QUESTIONS = [
    "Can you segment {sent} in this image? Please output the segmentation mask.",
    "Can you give the segmentation mask for {sent} in this image? Please respond with the segmentation mask.",
    "Can you highlight {sent} and output the corresponding segmentation mask? Please provide the segmentation mask.",
    "What is {sent} in this image? Please output the corresponding segmentation mask.",
    "What is {sent} in this image? Please generate a segmentation mask for this image.",
]

# 扩展 SHORT_QUESTIONS
SHORT_QUESTIONS += [
    "Please find {sent} in the image and output its segmentation mask.",
    "Locate {sent} in this picture and provide the segmentation mask.",
    "Show where {sent} is located by producing its segmentation mask.",
    "Draw the segmentation mask that corresponds to {sent} in the image.",
    "Can you outline {sent} in the image and give the segmentation mask?",

    "Which part of the image corresponds to {sent}? Please return a segmentation mask.",
    "Please mark {sent} in this image using a segmentation mask.",
    "Identify {sent} and output the binary segmentation mask.",
    "Please generate a mask that covers {sent} in this image.",
    "Could you segment {sent} and show me the corresponding mask?",
]

LONG_QUESTIONS = [
    "{sent} Please output the corresponding segmentation mask.",
    "{sent} Please generate a segmentation mask for this image.",
    "{sent} Please extract the segmentation mask.",
    "{sent} Please return the segmentation predictions as masks.",
    "{sent} Please segment the image.",
]

# 扩展 LONG_QUESTIONS
LONG_QUESTIONS += [
    "In this picture, {sent} — please provide a detailed segmentation mask.",
    "Please segment the region described as {sent} in this image.",
    "{sent} Try to highlight and return the segmentation mask of this region.",
    "For the given description {sent}, please output its segmentation mask.",
    "Given the image, {sent} — please compute and output a segmentation mask.",

    "{sent} Please localize this object in the image and generate a segmentation mask.",
    "You are asked to segment {sent} and provide its mask representation.",
    "{sent} Please produce a precise segmentation mask of this region.",
    "Please predict the segmentation mask corresponding to {sent}.",
    "{sent} Identify and mark the region by generating a segmentation mask.",
]

EXPLANATORY_QUESTIONS = [
    "{sent} Please explain why and output the corresponding segmentation mask.",
    "{sent} Please explain the reason and output the corresponding segmentation mask.",
    "{sent} Please give some explanation and output the corresponding segmentation mask.",
    "{sent} Please explain the reason and output the corresponding segmentation mask.",
    "{sent} Please give detailed explanation and output the corresponding segmentation mask.",
]

# 扩展 EXPLANATORY_QUESTIONS
EXPLANATORY_QUESTIONS += [
    "{sent} Describe your reasoning process and provide the segmentation mask.",
    "{sent} Please explain how you find it and output the mask.",
    "{sent} Explain why you identified this region and generate the segmentation mask.",
    "{sent} Provide your reasoning and the corresponding segmentation mask.",
    "{sent} Please show your reasoning and mark the segmentation mask.",

    "{sent} Please output the segmentation mask and briefly describe the reasoning.",
    "{sent} Please justify your segmentation result and output the mask.",
    "{sent} Please describe the evidence for your segmentation and output the mask.",
    "{sent} Please reason step by step and produce the segmentation mask.",
    "{sent} Please explain your visual reasoning process and provide the segmentation mask.",
]

MASK_ANSWER_LIST = [
    f"{DEFAULT_SEG_TOKEN}.",
    f"It is {DEFAULT_SEG_TOKEN}.",
    f"Sure, {DEFAULT_SEG_TOKEN}.",
    f"Sure, it is {DEFAULT_SEG_TOKEN}.",
    f"Sure, the segmentation result is {DEFAULT_SEG_TOKEN}.",
]

RLE_ANSWER_LIST = [
    f"{DEFAULT_RLE_TOKEN}.",
    f"It is {DEFAULT_RLE_TOKEN}.",
    f"Sure, {DEFAULT_RLE_TOKEN}.",
    f"Sure, it is {DEFAULT_RLE_TOKEN}.",
    f"Sure, the segmentation result is {DEFAULT_RLE_TOKEN}.",
]

MASK_CAPTION_ANSWER_LIST = [
    "{caption} {seg_token}.",
    "{caption} And it is {seg_token}.",
    "{caption} And {seg_token}.",
    "{caption} And the segmentation result is {seg_token}.",
]

GCG_QUESTION_LIST = [
    "Could you please give me a brief description of the image? Please respond with interleaved segmentation masks for the corresponding parts of the answer.",
    "Can you provide a brief description of the this image? Please output interleaved segmentation masks for the corresponding phrases.",
    "Please briefly describe the contents of the image. Please respond with interleaved segmentation masks for the corresponding parts of the answer.",
    "Could you give a brief explanation of what can be found within this picture? Please output interleaved segmentation masks for the corresponding phrases.",
    "Could you give me an brief explanation of this picture? Please respond with interleaved segmentation masks for the corresponding phrases.",
    "Could you provide me with a briefly analysis of this photo? Please output interleaved segmentation masks for the corresponding parts of the answer.",
]

GCG_ANSWER_LIST = [
    f"{DEFAULT_SEG_TOKEN}.",
    f"And {DEFAULT_SEG_TOKEN}.",
    f"The segmentation mask is {DEFAULT_SEG_TOKEN}.",
    f"And the segmentation mask is {DEFAULT_SEG_TOKEN}.",
]

P_FORMAT = DEFAULT_PSTART_TOKEN + "{}" + DEFAULT_PEND_TOKEN
INSTANCE_FORMAT = DEFAULT_INSTANCE_TOKEN + "{}"
C_FORMAT = "{} " + DEFAULT_CLS_TOKEN
P_C_FORMAT = DEFAULT_PSTART_TOKEN + "{}" + DEFAULT_PEND_TOKEN + DEFAULT_CLS_TOKEN

FORMAT_DICT = {
    "phrase": P_FORMAT,
    "cls": C_FORMAT,
    "all": P_C_FORMAT,
}

THINK_INSTRUCTION = ('You will analyze the image and extract all visual instances. '
                     'For each instance: '
                     '- assign a unique name such as "person-1", "tree-2", "fence-1" '
                     '- assign a normalized bounding box [x_min, y_min, x_max, y_max] in [0, 1] '
                     '- assign an RGB color [R, G, B] that will later be used to render segmentation masks. '
                     'Then output only a JSON object inside a <think>...</think> block, using this format: '
                     '{"caption": "...natural language caption...",'
                     '"instances": {"<name>": {"bbox": [x_min, y_min, x_max, y_max],"color": [R, G, B]}}}')

COCO_CATEGORIES = [
    {'id': 1, 'name': 'person', 'color': [220, 20, 60], 'isthing': 1, 'alias': ['human', 'people', 'pedestrian']},
    {'id': 2, 'name': 'bicycle', 'color': [119, 11, 32], 'isthing': 1, 'alias': ['bike', 'cycle']},
    {'id': 3, 'name': 'car', 'color': [0, 0, 142], 'isthing': 1, 'alias': ['auto', 'automobile']},
    {'id': 4, 'name': 'motorcycle', 'color': [0, 0, 230], 'isthing': 1, 'alias': ['motorbike', 'minibike, motorbike']},
    {'id': 5, 'name': 'airplane', 'color': [106, 0, 228], 'isthing': 1, 'alias': ['plane', 'aircraft', 'jet']},
    {'id': 6, 'name': 'bus', 'color': [0, 60, 100], 'isthing': 1, 'alias': ['coach']},
    {'id': 7, 'name': 'train', 'color': [0, 80, 100], 'isthing': 1, 'alias': ['locomotive', 'railway train']},
    {'id': 8, 'name': 'truck', 'color': [0, 0, 70], 'isthing': 1, 'alias': ['lorry', 'cargo truck']},
    {'id': 9, 'name': 'boat', 'color': [0, 0, 192], 'isthing': 1, 'alias': ['ship', 'vessel']},
    {'id': 10, 'name': 'traffic light', 'color': [250, 170, 30], 'isthing': 1,
     'alias': ['traffic signal', 'signal light']},
    {'id': 11, 'name': 'fire hydrant', 'color': [100, 170, 30], 'isthing': 1, 'alias': ['hydrant']},
    {'id': 13, 'name': 'stop sign', 'color': [220, 220, 0], 'isthing': 1, 'alias': ['stopboard']},
    {'id': 14, 'name': 'parking meter', 'color': [175, 116, 175], 'isthing': 1, 'alias': ['parking machine']},
    {'id': 15, 'name': 'bench', 'color': [250, 0, 30], 'isthing': 1, 'alias': ['seat', 'park bench']},
    {'id': 16, 'name': 'bird', 'color': [165, 42, 42], 'isthing': 1, 'alias': ['avian']},
    {'id': 17, 'name': 'cat', 'color': [255, 77, 255], 'isthing': 1, 'alias': ['kitten', 'feline']},
    {'id': 18, 'name': 'dog', 'color': [0, 226, 252], 'isthing': 1, 'alias': ['puppy', 'canine']},
    {'id': 19, 'name': 'horse', 'color': [182, 182, 255], 'isthing': 1, 'alias': ['stallion']},
    {'id': 20, 'name': 'sheep', 'color': [0, 82, 0], 'isthing': 1, 'alias': ['lamb']},
    {'id': 21, 'name': 'cow', 'color': [120, 166, 157], 'isthing': 1, 'alias': ['cattle', 'ox']},
    {'id': 22, 'name': 'elephant', 'color': [110, 76, 0], 'isthing': 1, 'alias': ['elephantidae']},
    {'id': 23, 'name': 'bear', 'color': [174, 57, 255], 'isthing': 1, 'alias': ['ursine']},
    {'id': 24, 'name': 'zebra', 'color': [199, 100, 0], 'isthing': 1, 'alias': ['zebra']},
    {'id': 25, 'name': 'giraffe', 'color': [72, 0, 118], 'isthing': 1, 'alias': ['giraffe']},
    {'id': 27, 'name': 'backpack', 'color': [255, 179, 240], 'isthing': 1, 'alias': ['rucksack', 'bag']},
    {'id': 28, 'name': 'umbrella', 'color': [0, 125, 92], 'isthing': 1, 'alias': ['parasol']},
    {'id': 31, 'name': 'handbag', 'color': [209, 0, 151], 'isthing': 1, 'alias': ['purse']},
    {'id': 32, 'name': 'tie', 'color': [188, 208, 182], 'isthing': 1, 'alias': ['necktie']},
    {'id': 33, 'name': 'suitcase', 'color': [0, 220, 176], 'isthing': 1, 'alias': ['luggage']},
    {'id': 34, 'name': 'frisbee', 'color': [255, 99, 164], 'isthing': 1, 'alias': ['flying disc']},
    {'id': 35, 'name': 'skis', 'color': [92, 0, 73], 'isthing': 1, 'alias': ['ski']},
    {'id': 36, 'name': 'snowboard', 'color': [133, 129, 255], 'isthing': 1, 'alias': ['snowboard']},
    {'id': 37, 'name': 'sports ball', 'color': [78, 180, 255], 'isthing': 1, 'alias': ['ball']},
    {'id': 38, 'name': 'kite', 'color': [0, 228, 0], 'isthing': 1, 'alias': ['kite']},
    {'id': 39, 'name': 'baseball bat', 'color': [174, 255, 243], 'isthing': 1, 'alias': ['bat']},
    {'id': 40, 'name': 'baseball glove', 'color': [45, 89, 255], 'isthing': 1, 'alias': ['mitt']},
    {'id': 41, 'name': 'skateboard', 'color': [134, 134, 103], 'isthing': 1, 'alias': ['skate']},
    {'id': 42, 'name': 'surfboard', 'color': [145, 148, 174], 'isthing': 1, 'alias': ['surfboard']},
    {'id': 43, 'name': 'tennis racket', 'color': [255, 208, 186], 'isthing': 1, 'alias': ['racquet']},
    {'id': 44, 'name': 'bottle', 'color': [197, 226, 255], 'isthing': 1, 'alias': ['container']},
    {'id': 46, 'name': 'wine glass', 'color': [171, 134, 1], 'isthing': 1, 'alias': ['goblet']},
    {'id': 47, 'name': 'cup', 'color': [109, 63, 54], 'isthing': 1, 'alias': ['mug']},
    {'id': 48, 'name': 'fork', 'color': [207, 138, 255], 'isthing': 1, 'alias': ['fork']},
    {'id': 49, 'name': 'knife', 'color': [151, 0, 95], 'isthing': 1, 'alias': ['knife']},
    {'id': 50, 'name': 'spoon', 'color': [9, 80, 61], 'isthing': 1, 'alias': ['spoon']},
    {'id': 51, 'name': 'bowl', 'color': [84, 105, 51], 'isthing': 1, 'alias': ['bowl']},
    {'id': 52, 'name': 'banana', 'color': [74, 65, 105], 'isthing': 1, 'alias': ['banana']},
    {'id': 53, 'name': 'apple', 'color': [166, 196, 102], 'isthing': 1, 'alias': ['apple']},
    {'id': 54, 'name': 'sandwich', 'color': [208, 195, 210], 'isthing': 1, 'alias': ['sandwich']},
    {'id': 55, 'name': 'orange', 'color': [255, 109, 65], 'isthing': 1, 'alias': ['citrus']},
    {'id': 56, 'name': 'broccoli', 'color': [0, 143, 149], 'isthing': 1, 'alias': ['broccoli']},
    {'id': 57, 'name': 'carrot', 'color': [179, 0, 194], 'isthing': 1, 'alias': ['carrot']},
    {'id': 58, 'name': 'hot dog', 'color': [209, 99, 106], 'isthing': 1, 'alias': ['sausage']},
    {'id': 59, 'name': 'pizza', 'color': [5, 121, 0], 'isthing': 1, 'alias': ['pizza']},
    {'id': 60, 'name': 'donut', 'color': [227, 255, 205], 'isthing': 1, 'alias': ['doughnut']},
    {'id': 61, 'name': 'cake', 'color': [147, 186, 208], 'isthing': 1, 'alias': ['cake']},
    {'id': 62, 'name': 'chair', 'color': [153, 69, 1], 'isthing': 1, 'alias': ['seat']},
    {'id': 63, 'name': 'couch', 'color': [3, 95, 161], 'isthing': 1, 'alias': ['sofa']},
    {'id': 64, 'name': 'potted plant', 'color': [163, 255, 0], 'isthing': 1, 'alias': ['houseplant', 'plant']},
    {'id': 65, 'name': 'bed', 'color': [119, 0, 170], 'isthing': 1, 'alias': ['sleeping bed']},
    {'id': 67, 'name': 'dining table', 'color': [0, 182, 199], 'isthing': 1, 'alias': ['dinner table']},
    {'id': 70, 'name': 'toilet', 'color': [0, 165, 120], 'isthing': 1, 'alias': ['wc', 'bathroom fixture']},
    {'id': 72, 'name': 'tv', 'color': [183, 130, 88], 'isthing': 1, 'alias': ['television']},
    {'id': 73, 'name': 'laptop', 'color': [95, 32, 0], 'isthing': 1, 'alias': ['notebook computer']},
    {'id': 74, 'name': 'mouse', 'color': [130, 114, 135], 'isthing': 1, 'alias': ['computer mouse']},
    {'id': 75, 'name': 'remote', 'color': [110, 129, 133], 'isthing': 1, 'alias': ['remote control']},
    {'id': 76, 'name': 'keyboard', 'color': [166, 74, 118], 'isthing': 1, 'alias': ['keyboard']},
    {'id': 77, 'name': 'cell phone', 'color': [219, 142, 185], 'isthing': 1, 'alias': ['mobile phone', 'smartphone']},
    {'id': 78, 'name': 'microwave', 'color': [79, 210, 114], 'isthing': 1, 'alias': ['microwave oven']},
    {'id': 79, 'name': 'oven', 'color': [178, 90, 62], 'isthing': 1, 'alias': ['oven']},
    {'id': 80, 'name': 'toaster', 'color': [65, 70, 15], 'isthing': 1, 'alias': ['toaster']},
    {'id': 81, 'name': 'sink', 'color': [127, 167, 115], 'isthing': 1, 'alias': ['basin']},
    {'id': 82, 'name': 'refrigerator', 'color': [59, 105, 106], 'isthing': 1,
     'alias': ['fridge', 'refrigerator, icebox']},
    {'id': 84, 'name': 'book', 'color': [142, 108, 45], 'isthing': 1, 'alias': ['book']},
    {'id': 85, 'name': 'clock', 'color': [196, 172, 0], 'isthing': 1, 'alias': ['watch']},
    {'id': 86, 'name': 'vase', 'color': [95, 54, 80], 'isthing': 1, 'alias': ['vase']},
    {'id': 87, 'name': 'scissors', 'color': [128, 76, 255], 'isthing': 1, 'alias': ['shears']},
    {'id': 88, 'name': 'teddy bear', 'color': [201, 57, 1], 'isthing': 1, 'alias': ['stuffed bear', 'plush toy']},
    {'id': 89, 'name': 'hair drier', 'color': [246, 0, 122], 'isthing': 1, 'alias': ['hair dryer']},
    {'id': 90, 'name': 'toothbrush', 'color': [191, 162, 208], 'isthing': 1, 'alias': ['toothbrush']},

    {'id': 92, 'name': 'banner', 'color': [255, 255, 128], 'isthing': 0, 'alias': ['sign', 'flag']},
    {'id': 93, 'name': 'blanket', 'color': [147, 211, 203], 'isthing': 0, 'alias': ['quilt']},
    {'id': 95, 'name': 'bridge', 'color': [150, 100, 100], 'isthing': 0, 'alias': ['bridge']},
    {'id': 100, 'name': 'cardboard', 'color': [168, 171, 172], 'isthing': 0, 'alias': ['paperboard']},
    {'id': 107, 'name': 'counter', 'color': [146, 112, 198], 'isthing': 0, 'alias': ['countertop']},
    {'id': 109, 'name': 'curtain', 'color': [210, 170, 100], 'isthing': 0, 'alias': ['drape']},
    {'id': 112, 'name': 'door-stuff', 'color': [92, 136, 89], 'isthing': 0, 'alias': ['door']},
    {'id': 118, 'name': 'floor-wood', 'color': [218, 88, 184], 'isthing': 0, 'alias': ['wood floor', 'wooden floor']},
    {'id': 119, 'name': 'flower', 'color': [241, 129, 0], 'isthing': 0, 'alias': ['plant flower']},
    {'id': 122, 'name': 'fruit', 'color': [217, 17, 255], 'isthing': 0, 'alias': ['fruits']},
    {'id': 125, 'name': 'gravel', 'color': [124, 74, 181], 'isthing': 0, 'alias': ['stones']},
    {'id': 128, 'name': 'house', 'color': [70, 70, 70], 'isthing': 0, 'alias': ['building']},
    {'id': 130, 'name': 'light', 'color': [255, 228, 255], 'isthing': 0, 'alias': ['lamp']},
    {'id': 133, 'name': 'mirror-stuff', 'color': [154, 208, 0], 'isthing': 0, 'alias': ['mirror']},
    {'id': 138, 'name': 'net', 'color': [193, 0, 92], 'isthing': 0, 'alias': ['mesh']},
    {'id': 141, 'name': 'pillow', 'color': [76, 91, 113], 'isthing': 0, 'alias': ['cushion']},
    {'id': 144, 'name': 'platform', 'color': [255, 180, 195], 'isthing': 0, 'alias': ['platform']},
    {'id': 145, 'name': 'playingfield', 'color': [106, 154, 176], 'isthing': 0, 'alias': ['sports field', 'field']},
    {'id': 147, 'name': 'railroad', 'color': [230, 150, 140], 'isthing': 0, 'alias': ['railway', 'tracks', 'rail']},
    {'id': 148, 'name': 'river', 'color': [60, 143, 255], 'isthing': 0, 'alias': ['river']},
    {'id': 149, 'name': 'road', 'color': [128, 64, 128], 'isthing': 0, 'alias': ['street', 'road, route', 'roadway']},
    {'id': 151, 'name': 'roof', 'color': [92, 82, 55], 'isthing': 0, 'alias': ['roof']},
    {'id': 154, 'name': 'sand', 'color': [254, 212, 124], 'isthing': 0, 'alias': ['sandy ground']},
    {'id': 155, 'name': 'sea', 'color': [73, 77, 174], 'isthing': 0, 'alias': ['ocean']},
    {'id': 156, 'name': 'shelf', 'color': [255, 160, 98], 'isthing': 0, 'alias': ['rack']},
    {'id': 159, 'name': 'snow', 'color': [255, 255, 255], 'isthing': 0, 'alias': ['snow']},
    {'id': 161, 'name': 'stairs', 'color': [104, 84, 109], 'isthing': 0, 'alias': ['staircase', 'stairway, staircase']},
    {'id': 166, 'name': 'tent', 'color': [169, 164, 131], 'isthing': 0, 'alias': ['tent']},
    {'id': 168, 'name': 'towel', 'color': [225, 199, 255], 'isthing': 0, 'alias': ['towel']},
    {'id': 171, 'name': 'wall-brick', 'color': [137, 54, 74], 'isthing': 0, 'alias': ['brick wall']},
    {'id': 175, 'name': 'wall-stone', 'color': [135, 158, 223], 'isthing': 0, 'alias': ['stone wall']},
    {'id': 176, 'name': 'wall-tile', 'color': [7, 246, 231], 'isthing': 0, 'alias': ['tile wall']},
    {'id': 177, 'name': 'wall-wood', 'color': [107, 255, 200], 'isthing': 0, 'alias': ['wood wall', 'wooden wall']},
    {'id': 178, 'name': 'water-other', 'color': [58, 41, 149], 'isthing': 0, 'alias': ['water']},
    {'id': 180, 'name': 'window-blind', 'color': [183, 121, 142], 'isthing': 0, 'alias': ['blinds']},
    {'id': 181, 'name': 'window-other', 'color': [255, 73, 97], 'isthing': 0, 'alias': ['window']},
    {'id': 184, 'name': 'tree-merged', 'color': [107, 142, 35], 'isthing': 0, 'alias': ['tree']},
    {'id': 185, 'name': 'fence-merged', 'color': [190, 153, 153], 'isthing': 0, 'alias': ['fence']},
    {'id': 186, 'name': 'ceiling-merged', 'color': [146, 139, 141], 'isthing': 0, 'alias': ['ceiling']},
    {'id': 187, 'name': 'sky-other-merged', 'color': [70, 130, 180], 'isthing': 0, 'alias': ['sky']},
    {'id': 188, 'name': 'cabinet-merged', 'color': [134, 199, 156], 'isthing': 0, 'alias': ['cabinet']},
    {'id': 189, 'name': 'table-merged', 'color': [209, 226, 140], 'isthing': 0, 'alias': ['table']},
    {'id': 190, 'name': 'floor-other-merged', 'color': [96, 36, 108], 'isthing': 0, 'alias': ['floor']},
    {'id': 191, 'name': 'pavement-merged', 'color': [96, 96, 96], 'isthing': 0,
     'alias': ['sidewalk', 'sidewalk, pavement']},
    {'id': 192, 'name': 'mountain-merged', 'color': [64, 170, 64], 'isthing': 0, 'alias': ['hill', 'mountain, mount']},
    {'id': 193, 'name': 'grass-merged', 'color': [152, 251, 152], 'isthing': 0, 'alias': ['grass', 'lawn']},
    {'id': 194, 'name': 'dirt-merged', 'color': [208, 229, 228], 'isthing': 0, 'alias': ['soil', 'ground', 'earth']},
    {'id': 195, 'name': 'paper-merged', 'color': [206, 186, 171], 'isthing': 0, 'alias': ['paper']},
    {'id': 196, 'name': 'food-other-merged', 'color': [152, 161, 64], 'isthing': 0,
     'alias': ['food', 'food, solid food']},
    {'id': 197, 'name': 'building-other-merged', 'color': [116, 112, 0], 'isthing': 0, 'alias': ['building']},
    {'id': 198, 'name': 'rock-merged', 'color': [0, 114, 143], 'isthing': 0, 'alias': ['rock', 'stone', 'rock, stone']},
    {'id': 199, 'name': 'wall-other-merged', 'color': [102, 102, 156], 'isthing': 0, 'alias': ['wall']},
    {'id': 200, 'name': 'rug-merged', 'color': [250, 141, 255], 'isthing': 0, 'alias': ['carpet', 'rug']},
]

ADE20K_SEM_SEG_CATEGORIES = [
    "wall",
    "building",
    "sky",
    "floor",
    "tree",
    "ceiling",
    "road, route",
    "bed",
    "window ",
    "grass",
    "cabinet",
    "sidewalk, pavement",
    "person",
    "earth, ground",
    "door",
    "table",
    "mountain, mount",
    "plant",
    "curtain",
    "chair",
    "car",
    "water",
    "painting, picture",
    "sofa",
    "shelf",
    "house",
    "sea",
    "mirror",
    "rug",
    "field",
    "armchair",
    "seat",
    "fence",
    "desk",
    "rock, stone",
    "wardrobe, closet, press",
    "lamp",
    "tub",
    "rail",
    "cushion",
    "base, pedestal, stand",
    "box",
    "column, pillar",
    "signboard, sign",
    "chest of drawers, chest, bureau, dresser",
    "counter",
    "sand",
    "sink",
    "skyscraper",
    "fireplace",
    "refrigerator, icebox",
    "grandstand, covered stand",
    "path",
    "stairs",
    "runway",
    "case, display case, showcase, vitrine",
    "pool table, billiard table, snooker table",
    "pillow",
    "screen door, screen",
    "stairway, staircase",
    "river",
    "bridge, span",
    "bookcase",
    "blind, screen",
    "coffee table",
    "toilet, can, commode, crapper, pot, potty, stool, throne",
    "flower",
    "book",
    "hill",
    "bench",
    "countertop",
    "stove",
    "palm, palm tree",
    "kitchen island",
    "computer",
    "swivel chair",
    "boat",
    "bar",
    "arcade machine",
    "hovel, hut, hutch, shack, shanty",
    "bus",
    "towel",
    "light",
    "truck",
    "tower",
    "chandelier",
    "awning, sunshade, sunblind",
    "street lamp",
    "booth",
    "tv",
    "plane",
    "dirt track",
    "clothes",
    "pole",
    "land, ground, soil",
    "bannister, banister, balustrade, balusters, handrail",
    "escalator, moving staircase, moving stairway",
    "ottoman, pouf, pouffe, puff, hassock",
    "bottle",
    "buffet, counter, sideboard",
    "poster, posting, placard, notice, bill, card",
    "stage",
    "van",
    "ship",
    "fountain",
    "conveyer belt, conveyor belt, conveyer, conveyor, transporter",
    "canopy",
    "washer, automatic washer, washing machine",
    "plaything, toy",
    "pool",
    "stool",
    "barrel, cask",
    "basket, handbasket",
    "falls",
    "tent",
    "bag",
    "minibike, motorbike",
    "cradle",
    "oven",
    "ball",
    "food, solid food",
    "step, stair",
    "tank, storage tank",
    "trade name",
    "microwave",
    "pot",
    "animal",
    "bicycle",
    "lake",
    "dishwasher",
    "screen",
    "blanket, cover",
    "sculpture",
    "hood, exhaust hood",
    "sconce",
    "vase",
    "traffic light",
    "tray",
    "trash can",
    "fan",
    "pier",
    "crt screen",
    "plate",
    "monitor",
    "bulletin board",
    "shower",
    "radiator",
    "glass, drinking glass",
    "clock",
    "flag",  # noqa
]


def tag_categories(categories, format=P_FORMAT, delimiter=', '):
    formatted_categories = []
    for category in categories:
        category = (
            category.replace("-merged", "")
            .replace("-other", "")
            .replace("-stuff", "")
            .replace("-negative", "")
            # .replace("-", " ")
            .lower()
            .strip()
        )
        category = format.format(category)
        formatted_categories.append(category)

    formatted_categories = delimiter.join(formatted_categories)
    return formatted_categories


if __name__ == '__main__':
    import yaml

    cat_dict = {}
    for contiguous_id, cat in enumerate(COCO_CATEGORIES):
        category = (
            cat["name"]
            .replace("-merged", "")
            .replace("-other", "")
            .replace("-stuff", "")
            .replace("-negative", "")
            .replace("-", " ")
            .lower()
        )

        cat_dict[category] = {
            "id": cat["id"],
            "name": cat["name"],
            "contiguous_id": contiguous_id,
            "color": cat["color"],
            "isthing": cat["isthing"],
        }

    with open("coco_categories.yaml", "w") as f:
        yaml.dump(cat_dict, f, sort_keys=False, allow_unicode=True, default_flow_style=False)

    ade_dict = {
        cat: {
            "id": i,
            "contiguous_id": i,
            "name": cat,
        }
        for i, cat in enumerate(ADE20K_SEM_SEG_CATEGORIES)
    }

    with open("ade_categories.yaml", "w") as f:
        yaml.dump(ade_dict, f, allow_unicode=True, sort_keys=False)
